### ISSUE TITLE
Need help installing CTHYB in the Anaconda environment

### ISSUE THREAD

**Issue by phystd** [TRIQS/cthyb#128]
I have been trying to install CTHYB within the Anaconda environment.  When I execute the following commands 
cmake -DMeasureG2=OFF ../cthyb.src 

at the prompt, I get

cmake: symbol lookup error: /usr/lib64/libssh.so.4: undefined symbol: EVP_KDF_CTX_new_id, version OPENSSL_1_1_1d

How can I fix this?

**Comment by phystd** [comment]
Does anyone have any help on how to fix this issue? I have posted it both to the packaging issue and here. I would appreciate any help with fixing this. Thanks.

**Comment by the-hampel** [comment]
Hi Phystd,
I don't have much experience with the Anaconda packages, but I know it is a bit tedious to compile the triqs applications against a conda installed triqs version, because you need to use exactly the same compilers and libs that where used to compile triqs. We are right now making also the triqs applications available on conda forge. See for example: https://github.com/conda-forge/triqs_cthyb-feedstock (the dfttools package is also available). Would it be an option for you to use the conda forge packages, or do you need a special version of cthyb? Maybe you can give this package a try. They are relatively new (released this week). Let me know if you have questions with this. 

If the problem still persists I can try to redo your steps on a virtual machine. You are using miniconda in pythn 2.7 version with the triqs package, and then try to manually install cthyb? 

Best,
Alex

**Comment by Wentzell** [comment]
Dear @phystd @the-hampel,

I am wrapping up final problems in the triqs_cthyb conda package.
I will let you know as soon as it is functional. It will then no longer be necessary to compile cthyb.

**Comment by Wentzell** [comment]
@phystd Please try to install cthyb into your conda environment with

```
conda install -c conda-forge triqs_cthyb
```

**Comment by phystd** [comment]
Dear Wentzell,

The installation command worked perfectly within myenv. The commands that you provided now work in OpenSuse (installed in virtual box) using the Anaconda package environment. 
I understand that this command should work generally too for other Linux distributions. I can generate the tutorial plots using CTHYB. Thank you!

the-hampel, thanks for the suggestions.

**Comment by Wentzell** [comment]
@phystd 
I am glad to hear that everything is working now.
Can you please close both issues?

**Comment by phystd** [comment]
Will do. Thanks.
