### ISSUE TITLE
Add complex flags for c++ tests

### ISSUE THREAD

**Issue by pseth** [TRIQS/cthyb#45]
Reminder to self.

**Comment by krivenko** [comment]
Do you mean that one has to define `HYBRIDISATION_IS_COMPLEX` and/or `LOCAL_HAMILTONIAN_IS_COMPLEX` in C++ tests in agreement with the compilation of `libcthyb_c.so`?

More generally, one has to take care of these flags in case of any C++ program linked to `libcthyb_c.so`. Otherwise, the solver will pretend to run without problem and return some weird results (I saw this with my own eyes).

In my opinion, there is a better approach used by many GNU projects. We should preprocess `config.hpp` and embed the macros into its text. The preprocessed file can then be used to build the shared library and the tests, as well as any 3d-party C++ application.

**Comment by parcollet** [comment]
closed by c259c2be065b5c8f08f78326d554b795930bd256
