### ISSUE TITLE
Solver with positive_frequencies_only

### ISSUE THREAD

**Issue by GingrasO** [TRIQS/cthyb#73]
Hello there,

I am currently working on interfacing the ABINIT package with TRIQS/CTHYB-1.4 and I have encountered a problem. A previous interfacing was performed with the 1.3 version and worked well, but some changes in the 1.4 version complicates our updating process.

In ABINIT, we only look at positive frequencies of the green's function. We put the electronic structure's code data in an object like
`gf<imfreq> delta_iw = gf<imfreq>{{beta, Fermion, Nfreq, positive_frequencies_only}, {num_orbitals,num_orbitals}};`
but at some point, I need to do
`solver_core solver(beta, gf_struct, Nfreq, Ntau, Nl);
solver.G0_iw()[0] = triqs::gfs::inverse( g0_iw );`

I got an error saying the mesh was not compatible and looking at the solver_core.cpp code, I don't see any way to make `solver._G0_iw` positive_frequencies_only.

Is there any way to make the solver's containers Green's functions positive_frequencies_only? Any idea otherwise on how to solve this problem?
Thanks a lot!
Olivier Gingras

**Comment by parcollet** [comment]
In 1.4, the green function are stored on the entire Matsubara axis.
Positively_only was kept to built higher dimension vertices where memory usage can be an issue, 
but for one variable gf, we recommend not to use it at all any more
(Python version even do not have this option any more).

While the previous storage of >0 matsubara was correct in most cases, it could not handle 
complex gf needed in the case of spin orbit. 
We generalised them and decided to always store the full
matsubara axis, as it is simpler and prevents a lot of possible errors for users.

So simply use
gf<imfreq> delta_iw = gf<imfreq>{{beta, Fermion, Nfreq}, ....}

PS 1 : besides, better to say (why repeat the type ??)
auto delta_iw = gf<imfreq>{{beta, Fermion, Nfreq}, ....}

PS2 : if you load an ancien h5 file, the conversion will be automatic, and in the new files
the full axis will be stored.

**Comment by GingrasO** [comment]
Excellent! We will make sure the upgrade to version 1.4 includes all the imaginary axis and spin orbit coupling. Thank you!

**Comment by parcollet** [comment]
PS : 
spin orbit coupling, yes but 
- I would like to see more tests
- the sign problem is very quickly an issue with them...

**Comment by GingrasO** [comment]
We sometimes treat only one spin in our calculations. Also, spin orbit coupling should not break time reversal symmetry if there are no moments associated with the correlated atoms. In such cases, the Green function should symmetric on the positive and negative imaginary frequencies, is that right?

In such case, couldn't it be interesting to treat only positive frequencies, to reduce calculation time and memory?

**Comment by parcollet** [comment]
yes it is symmetric.
one would indeed save some memory usage and calculation time, but that is negligible in real computations since the computations are dominated by the solver by far (the QMC solver internally uses another representation of gf anyway), and are not memory bound (memory for a gf is much lower than a vertex e.g.).
So it is a balance : one loses some memory and a bit of time, but gains a lot of simplicity for the code (you have to check for this flag in quite a few places) and diminish a serious source of errors for users (if you use positively_only where you should not, the error is often not easy to spot ...).
We kept positive_only to make the mesh for the vertex functions, (for one variable) where indeed the memory waste would become quickly unacceptable.
And we can always use it internally in a computation if it become important for speed.
But I would rather keep the API simple, with a general gf only.
