### ISSUE TITLE
Question regarding solver initialization (G_tau and G_l)

### ISSUE THREAD

**Issue by the-hampel** [TRIQS/cthyb#98]
Hi,

When one initializes the solver (for simplicity I call my solver instance `S`), also some BlockGf objects are initialized as well ([https://github.com/TRIQS/cthyb/blob/master/python/triqs_cthyb/solver.py](url)). For example after the init process I can access `S.G_iw` and put in there whatever I want. So something like this works totally fine:
`S[icrsh].G_iw[spin_channel] << S[imp_source].G_iw[target_channel]`
where I copy a spin_channel from one imp solver instance to another. This works as expected. 

However, if I want to access `S.G_tau` I encounter a problem. In principle `S.G_tau` is not initialized upon solver init, when I understood the python source code correctly. But something is there. If I want to built a new BlockGf and set it to `S.G_tau` I get an error. `S.G_tau << G_tau_empy` or `S.G_tau = G_tau_empy` both don't work. I get the error: 
"TypeError: unsupported operand type(s) for <<: 'NoneType' and 'BlockGf'" or 
"AttributeError: attribute 'G_tau' of 'triqs_cthyb.solver_core.SolverCore' objects is not writable".

When I do `dir(S[icrsh].G_tau)` I can see that it is more or less nothing, but the name is taken:
```
>>> print dir(S[icrsh].G_tau)
['__class__', '__delattr__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__']
```
I would like to understand where the solver does this in the c++ part, since I cannot find it in the init routines? And, would it be useful to properly init the `S.G_tau` BlockGf in python (same for `S.G_l`)? Or is this behavior on purpose to protect the namespace, since only when I call S.solve(...) it is decided if `S.G_tau` and `S.G_l` are needed? I noticed after I run the solver once with `measure_G_tau = True` everything works as expected.

I know it can be a bit spurious to modify those elements, but I just don't understand this empty nonetype object and why not init it them properly. Or maybe I did something completely wrong...

Best,
Alex

**Comment by HugoStrand** [comment]
Dear Alex,

Thank you for the very relevant questions, here is an attempt at explaining the current rationale.

The containers (`G_tau`, `G_l`) that are results of sampling in the C++ part of `cthyb` are members of the `triqs_cthyb.Solver` by inheritance from the `triqs_cthyb.SolverCore` class, that in turn is the wrapped c++ solver class.

Due to backward compatibility there are a couple of additional containers that are handled by the python part (`triqs_cthyb.Solver` again). Those are the Green's functions that are computed from the (optional) tail fit, i.e. `Sigma_iw` and `G_iw`. Since these things live in only in pure python they unfortunately behave different.

The containers that are direct results of sampling (`G_tau`, `G_l`, ...) are allocated inside the c++ code in the call to the solve method, at the point when a measurement is enabled. When a measurement is disabled the container will instead be empty (under the hood this is done using `std::optional<gf<...>>`). 

The rationale for this is to not be forced to allocate containers (Green's functions) for measurements that are not enabled. This is important, in particular, for the two particle Green's function measurements which are in general very large objects.

In general I think it is a good approach not to rely on modifying the measurement results by hand.

Please let me know if this makes things clearer. :)

Cheers, Hugo

**Comment by the-hampel** [comment]
Hi Hugo,
thanks a lot for your explanation. Then everything works as intended, I just wasn't sure because some containers where proper BlockGfs and some not. Therefore, I created now other containers that hold/save the data that I want to store, that are accessible by no default namespaces. For me everything is fine now. 

Maybe one last comment: from [https://triqs.github.io/cthyb/master/reference/solver.html](url) it looks to me as if all these Green function variables that are listed below the __init__ are initialized, but G_tau and G_l are clearly not. I don't know but maybe one could make this a bit clearer in the doc by just adding to those a sentence that they are initialized upon the solve call or something. 

Otherwise this is solved for me. ;-)
